#######################################################################################
# Book settings
title: Introduction to Programming
author: University of Oslo, Erik Winge, Eirill Strand Hauge
logo: images/uio_logo_small.svg

# Short description about the book
description: >-
  Course material for "Introduction to Programming"

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false
  use_repository_button       : true
  use_repository_button       : true
  use_edit_page_button        : true

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/scriptotek/programming-for-lawyers
  #path_to_book                : "mini_book"

launch_buttons:
  notebook_interface          : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url               : "https://mybinder.org"
  jupyterhub_url              : "https://jupyterhub.uio.no/"

# latex:
#   latex_engine                : "xelatex"
#   latex_documents:
#     targetname: book.tex
