#######################################################################################
# Book settings
title: Introduction to Programming
author: University of Oslo, Erik Winge, Eirill Strand Hauge
logo: images/uio_logo_small.svg

# Short description about the book
description: >-
  Course material for "Programming for Librarians"

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : auto

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false
  use_repository_button       : true
  use_issues_button           : true
  use_edit_page_button        : true


#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/scriptotek/programming
  #path_to_book                : "mini_book"
  branch                      : master  # Which branch of the repository should be used when creating links

launch_buttons:
  notebook_interface          : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url               : "https://mybinder.org"
  jupyterhub_url              : "https://jupyterhub.uio.no"
  colab_url                   : "https://colab.research.google.com"

# latex:
#   latex_engine                : "xelatex"
#   latex_documents:
#     targetname: book.tex
