name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: install
        run: |
          python --version
          python -m pip install setuptools
          python -m pip install -r requirements.txt
            
      - name: build 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          
          cd $GITHUB_WORKSPACE
          git init 
          git config user.name "Github Actions"
          git config user.email "github-actions-bot@users.noreply.github.com"
          REPOSITORY_PATH="https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          
          git checkout master 
          jupyter-book build .

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: ./_build/html
